Repository replicatedhq/replicated-docs, pull requests merged in 2022-07, with the labels that each got.

#435 release v2022.07.01-0
  docs/release-notes/rn-kubernetes-installer.md
Labels: type::docs

#436 release notes for kots v1.74.0
  docs/release-notes/rn-app-manager.md
Labels: type::chore, team::orange

#429 docs: installer preflight check
  docs/vendor/packaging-embedded-kubernetes.md
Labels: type::feature, team::orange

#437 release notes for kurl v2022.07.01-1
  docs/release-notes/rn-kubernetes-installer.md
Labels: type::chore, type::docs, team::orange

#438 Add app manager version for installer preflight
  docs/vendor/packaging-embedded-kubernetes.md
Labels: type::feature, team::orange

#441 Create policies-vulnerability-patch.md
  docs/vendor/policies-vulnerability-patch.md
Labels: type::docs

#440 Fix badly formatted note
  docs/vendor/helm-overview.md
Labels: type::chore, team::orange

#446 Clarify you can upgrade directly from OpenEBS 1.x to 3.x
  docs/release-notes/rn-kubernetes-installer.md
Labels: type::feature, team::orange

#449 Change installer feature to beta and add latest and .x requirement
  docs/vendor/packaging-embedded-kubernetes.md
Labels: type::feature, team::orange

#452 change process
  docs/vendor/helm-install.md
Labels: type::docs

#453 release notes
  docs/release-notes/rn-app-manager.md
  docs/release-notes/rn-kubernetes-installer.md
Labels: type::chore, team::orange

#471 add version for required releases
  docs/vendor/releases-promoting.md
Labels: type::docs

#490 KOTS 1.78.0 release notes
  docs/release-notes/rn-app-manager.md
Labels: type::chore
